(()=>{'use strict';
 const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
 const read=k=>{try{return localStorage.getItem(k);}catch{return null;}},write=(k,v)=>{try{localStorage.setItem(k,v);}catch{}};
 const account=$('#account-dialog'),question=$('#question-dialog'),privacy=$('#privacy-dialog'),discovery=$('#discovery-dialog');
 let user=null,favorites=new Set(),authMode='login',allProducts=[],pendingSave=null,toastTimer;
 for(const id of ['catalog-data','product-data']){const el=document.getElementById(id);if(el){try{const data=JSON.parse(el.textContent);allProducts=Array.isArray(data)?data:[data];}catch{}}}
 const api=async(path,body)=>{const response=await fetch(path,{...(body!==undefined?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),credentials:'same-origin',signal:AbortSignal.timeout(20000)});const data=await response.json();if(!response.ok)throw new Error(data.message||'Please try again.');return data;};
 function toast(text){const el=$('#site-toast');el.textContent=text;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,4500);}
 function modal(el){$$('dialog[open]').forEach(d=>d.close());el.showModal();}
 $$('[data-close-service]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
 $$('.service-dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
 function auth(mode){authMode=mode;$('#account-auth').hidden=false;$('#account-profile').hidden=true;$('#account-name-wrap').hidden=mode!=='signup';$('#account-name').required=mode==='signup';$('#recovery-wrap').hidden=mode!=='recover';$('#recovery-input').required=mode==='recover';$('#account-password').autocomplete=mode==='login'?'current-password':'new-password';$('#password-label').textContent=mode==='recover'?'New password':'Password';$('#account-submit').textContent=mode==='signup'?'Create account':mode==='recover'?'Recover account':'Sign in';$('#account-status').textContent='';$$('[data-auth-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.authMode===mode)));}
 $$('[data-auth-mode]').forEach(b=>b.addEventListener('click',()=>auth(b.dataset.authMode)));
 function favoriteStates(){$$('[data-favorite]').forEach(b=>{const saved=favorites.has(b.dataset.favorite);b.setAttribute('aria-pressed',String(saved));b.classList.toggle('is-saved',saved);b.setAttribute('aria-label',(saved?'Remove saved product: ':'Save product: ')+(b.dataset.title||b.dataset.favorite));});$$('[data-account-label]').forEach(el=>el.textContent=user?'My favorites':'My account');}
 async function profile(){
  $('#account-auth').hidden=true;$('#account-profile').hidden=false;$('#account-greeting').textContent='Hello, '+user.name+'. Your favorites are ready when you are.';favoriteStates();
  if(favorites.size&&!Array.from(favorites).every(s=>allProducts.some(p=>p.sku===s))){try{const r=await fetch('/catalog/products.json',{signal:AbortSignal.timeout(10000)});if(r.ok)allProducts=(await r.json()).products;}catch{}}
  const list=$('#saved-products');list.replaceChildren();
  if(!favorites.size){const p=document.createElement('p');p.textContent='Your collection starts here. Tap the heart on a product to save it.';list.append(p);}
  for(const sku of favorites){const p=allProducts.find(x=>x.sku===sku);if(!p)continue;const a=document.createElement('a');a.className='saved-item';a.href=p.url;const img=document.createElement('img');img.src=p.thumbnail||p.image;img.alt='';img.width=64;img.height=64;img.loading='lazy';const name=document.createElement('span');name.textContent=p.title;const price=document.createElement('strong');price.textContent='$'+p.price.toFixed(2)+' USD';a.append(img,name,price);list.append(a);}
 }
 async function refresh(){const data=await api('/api/account/me');user=data.user;favorites=new Set(data.favorites||[]);favoriteStates();return data;}
 async function openAccount(mode='login'){modal(account);$('#account-status').textContent='';if(user)await profile();else auth(mode);write('elvarins-discovery-dismissed',String(Date.now()));}
 $$('[data-open-account]').forEach(b=>b.addEventListener('click',()=>openAccount(b.dataset.openAccount)));
 $('#account-form').addEventListener('submit',async e=>{e.preventDefault();if(!e.target.reportValidity())return;const button=$('#account-submit'),status=$('#account-status');button.disabled=true;status.textContent='Please wait…';try{const fields=Object.fromEntries(new FormData(e.target));const data=await api('/api/account/'+authMode,fields);user=data.user;await refresh();e.target.reset();if(data.recoveryCode){$('#recovery-code').textContent=data.recoveryCode;$('#recovery-notice').hidden=false;}await profile();status.textContent=authMode==='signup'?'Your account is ready. Save your recovery code before closing.':'You are signed in.';if(pendingSave){await saveFavorite(pendingSave,true);pendingSave=null;await profile();}}catch(error){status.textContent=error.message;}finally{button.disabled=false;}});
 $('#account-logout').addEventListener('click',async()=>{try{await api('/api/account/logout',{});user=null;favorites.clear();$('#recovery-code').textContent='';$('#recovery-notice').hidden=true;auth('login');favoriteStates();toast('You have signed out.');}catch(error){$('#account-status').textContent=error.message;}});
 $('#download-recovery').addEventListener('click',()=>{const code=$('#recovery-code').textContent;if(!code)return;const url=URL.createObjectURL(new Blob(['Elvarins account recovery\nEmail: '+user.email+'\nRecovery code: '+code+'\nKeep this file private. Use My account > Recover account if you forget your password.\n'],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='elvarins-account-recovery.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 async function saveFavorite(sku,saved){await api('/api/account/favorite',{sku,saved});saved?favorites.add(sku):favorites.delete(sku);favoriteStates();toast(saved?'Added to your saved collection.':'Removed from your saved collection.');}
 $$('.product-card').forEach(card=>{const p=allProducts.find(p=>p.sku===card.dataset.sku);if(!p)return;const b=document.createElement('button');b.className='favorite-button';b.type='button';b.dataset.favorite=p.sku;b.dataset.title=p.title;b.setAttribute('aria-pressed','false');b.setAttribute('aria-label','Save product: '+p.title);b.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/></svg>';card.append(b);});
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-favorite]');if(!b)return;if(!user){pendingSave=b.dataset.favorite;await openAccount('signup');return;}b.disabled=true;try{await saveFavorite(b.dataset.favorite,!favorites.has(b.dataset.favorite));}catch(error){toast(error.message);}finally{b.disabled=false;}});
 function openQuestion(topic='product',sku='',message=''){modal(question);$('#question-topic').value=topic;$('#question-sku').value=sku;$('#question-message').value=message;$('#question-status').textContent='';if(user){$('#question-form [name="name"]').value=user.name;$('#question-form [name="email"]').value=user.email;}}
 $$('[data-question-topic]').forEach(b=>b.addEventListener('click',()=>openQuestion(b.dataset.questionTopic)));
 $$('[data-product-question]').forEach(b=>b.addEventListener('click',()=>{const sku=$('#detail-sku')?.textContent||allProducts[0]?.sku||'',qty=$('#shipping-qty')?.value||'1',zip=$('#shipping-zip')?.value||'';openQuestion('shipping',sku,'Please confirm availability, shipping and any applicable taxes before purchase.\nQuantity: '+qty+(zip?'\nDelivery ZIP: '+zip:''));}));
 $('#question-form').addEventListener('submit',async e=>{e.preventDefault();if(!e.target.reportValidity())return;const b=e.target.querySelector('[type="submit"]'),status=$('#question-status');b.disabled=true;status.textContent='Sending your request…';try{const data=await api('/api/inquiries',Object.fromEntries(new FormData(e.target)));status.textContent=data.message+' Reference: '+data.reference;e.target.reset();}catch(error){status.textContent=error.message;}finally{b.disabled=false;}});
 const gpc=navigator.globalPrivacyControl===true;
 function openPrivacy(){modal(privacy);$('#privacy-optout').checked=gpc||read('elvarins-privacy-optout')!=='false';$('#privacy-optout').disabled=gpc;$('#gpc-status').textContent=gpc?'Global Privacy Control is detected. Your opt-out is enabled.':'No Global Privacy Control signal was detected. You can save your choice below.';$('#privacy-status').textContent='';}
 if(gpc)write('elvarins-privacy-optout','true');$$('[data-open-privacy]').forEach(b=>b.addEventListener('click',openPrivacy));
 $('#save-privacy').addEventListener('click',()=>{write('elvarins-privacy-optout',String(gpc||$('#privacy-optout').checked));$('#privacy-status').textContent='Your privacy choice is saved for this browser.';});
 const reduced=matchMedia('(prefers-reduced-motion: reduce)'),paused=read('elvarins-motion-paused')==='true';if(paused)document.documentElement.classList.add('motion-paused');
 const motionButton=document.createElement('button');motionButton.type='button';motionButton.className='footer-link';motionButton.textContent=paused?'Enable motion':'Pause motion';motionButton.setAttribute('aria-pressed',String(paused));motionButton.addEventListener('click',()=>{const stopped=document.documentElement.classList.toggle('motion-paused');write('elvarins-motion-paused',String(stopped));motionButton.textContent=stopped?'Enable motion':'Pause motion';motionButton.setAttribute('aria-pressed',String(stopped));});$('.footer-bottom')?.append(motionButton);
 if(!reduced.matches&&!paused&&'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.remove('reveal-pending');observer.unobserve(entry.target);}}),{threshold:.08});$$('.world-card,.section-head,.about-grid,.department,.faq-grid,.contact-panel').forEach(el=>{el.classList.add('reveal-pending');observer.observe(el);});}
 const hero=$('.hero-visual');if(hero&&!reduced.matches&&matchMedia('(pointer:fine)').matches){let raf;hero.addEventListener('pointermove',e=>{if(document.documentElement.classList.contains('motion-paused'))return;cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{const r=hero.getBoundingClientRect();hero.style.setProperty('--tilt-x',((e.clientY-r.top)/r.height-.5)*-5+'deg');hero.style.setProperty('--tilt-y',((e.clientX-r.left)/r.width-.5)*5+'deg');});});hero.addEventListener('pointerleave',()=>{cancelAnimationFrame(raf);hero.style.setProperty('--tilt-x','0deg');hero.style.setProperty('--tilt-y','0deg');});}
 let scrolled=false;addEventListener('scroll',()=>{scrolled=scrollY>400;$('#back-to-top').hidden=!scrolled;},{passive:true});$('#back-to-top').addEventListener('click',()=>scrollTo({top:0,behavior:reduced.matches?'auto':'smooth'}));
 discovery.addEventListener('close',()=>write('elvarins-discovery-dismissed',String(Date.now())));
 setTimeout(()=>{const dismissed=Number(read('elvarins-discovery-dismissed')||0);if(!user&&scrolled&&Date.now()-dismissed>7*86400000&&!$('dialog[open]')&&document.visibilityState==='visible'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))modal(discovery);},45000);

 $$('[data-department-request]').forEach(b=>b.addEventListener('click',()=>{modal(question);$('#question-topic').value='general';$('#question-sku').value='';$('#question-message').value='Department: '+b.dataset.departmentRequest+'\nI am looking for: ';$('#question-status').textContent='';}));
 const heroCopy={transformers:['Find your next<br><em>Transformers favorite.</em>','Explore character figures for your collection, with clear item details and individual retail prices.'],marvel:['Bring your heroes<br><em>into focus.</em>','Discover Marvel figures and character collectibles, ready to explore one item at a time.'],funko:['Small figures.<br><em>Big personalities.</em>','Find a character for your shelf with our selection of Funko Pop! vinyl figures.']};
 $$('[data-hero-collection]').forEach(b=>b.addEventListener('click',()=>{const slug=b.dataset.heroCollection,p=allProducts.find(x=>x.collection===slug);if(!p)return;$('.hero-copy h1').innerHTML=heroCopy[slug][0];$('.hero-copy>p').textContent=heroCopy[slug][1];const cta=$('.hero-actions a');cta.href='/collections/'+slug;cta.textContent='Explore the collection →';const img=$('.hero-feature img');img.src=p.image;img.alt=p.title;delete img.dataset.fallback;const link=$('.hero-feature a');link.href=p.url;link.textContent='Explore this character ↗';$$('[data-hero-collection]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));}));

 async function newsletterSubmit(form,status,action){const b=form.querySelector('button[type=submit]');b.disabled=true;status.textContent='Saving your preference…';try{const data=await api('/api/newsletter',{email:form.elements.email.value,action,consent:form.elements.consent?.checked===true,website:form.elements.website?.value||''});status.textContent=data.message;form.reset();}catch(error){status.textContent=error.message;}finally{b.disabled=false;}}
 $('#newsletter-form')?.addEventListener('submit',e=>{e.preventDefault();newsletterSubmit(e.target,$('#newsletter-status'),'subscribe');});
 $('#newsletter-unsubscribe')?.addEventListener('submit',e=>{e.preventDefault();newsletterSubmit(e.target,$('#unsubscribe-status'),'unsubscribe');});
 $('#order-help-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.target,b=f.querySelector('button[type=submit]'),status=$('#order-help-status');b.disabled=true;status.textContent='Sending your request…';try{const v=Object.fromEntries(new FormData(f)),data=await api('/api/inquiries',{name:v.name,email:v.email,website:v.website||'',topic:'shipping',sku:'',message:'Order update request. Purchase reference: '+v.orderReference+'\n'+v.message});status.textContent=data.message+' Request reference: '+data.reference;f.reset();}catch(error){status.textContent=error.message;}finally{b.disabled=false;}});
 refresh().catch(()=>{});
})();
