import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const products=JSON.parse(await readFile(new URL('../catalog/products.json',import.meta.url),'utf8')).products;
const nodes=new Map();
function node(id){if(!nodes.has(id))nodes.set(id,{value:'',hidden:false,listeners:{},addEventListener(event,fn){this.listeners[event]=fn;},querySelectorAll(){return [];},focus(){this.focused=true;},scrollIntoView(){}});return nodes.get(id);}
node('catalog-data').textContent=JSON.stringify(products);
const cards=products.map(p=>({dataset:{sku:p.sku},hidden:false}));
node('product-grid').querySelectorAll=()=>cards;
node('product-grid').appendChild=()=>{};
node('product-sort').value='featured';
const document={getElementById:node,querySelectorAll:()=>[]};
vm.runInNewContext(await readFile(new URL('../catalog.js',import.meta.url),'utf8'),{document,Intl,URLSearchParams,location:{search:''}});
const search=(text)=>{node('product-search').value=text;node('product-search').listeners.input();return cards.filter(c=>!c.hidden).map(c=>c.dataset.sku);};
assert.deepEqual(search('gundam wing'),['BLF2279763']);
assert.deepEqual(search('GUNDAM    WING'),['BLF2279763']);
assert.ok(search('spider man').includes('HSG3442'));
assert.deepEqual(search('BLF-2279763'),['BLF2279763']);
assert.deepEqual(search('gundam Bandai'),['BLF2279763']);
assert.deepEqual(search('not-a-real-character'),[]);
assert.deepEqual(search('日本語'),[]);
search('');node('brand-filter').value='Bandai Hobby Gunpla';node('brand-filter').listeners.change();
assert.equal(node('result-count').textContent,'1 product · showing 1');
assert.equal(node('reset-catalog-filters').hidden,false);
node('reset-catalog-filters').listeners.click();
assert.equal(node('brand-filter').value,'');assert.equal(node('reset-catalog-filters').hidden,true);
assert.equal(node('result-count').textContent,products.length+' products · showing 12');
node('load-more').listeners.click();assert.equal(cards.filter(c=>!c.hidden).length,24);
console.log('PASS: catalog search, punctuation, word order, manufacturer filters, reset and pagination');
